[dev]
  command = "yarn start"
  port = 8888
  framework = "create-react-app"
  autoLaunch = true

# Shared config for build
[build]
  command = "yarn build"
  [build.environment]
    GENERATE_SOURCEMAP = "false"
    REACT_APP_MODE = "testnet"
    REACT_APP_GOOGLE_ANALYTICS = "GTM-KTSX2PL"

[context.production]
  [context.production.environment]
    REACT_APP_MODE = "mainnet"
    REACT_APP_GOOGLE_ANALYTICS = "GTM-PT56KWJ"

# PR deployments (previews)
[context.deploy-preview]
  [context.deploy-preview.environment]
    REACT_APP_MODE = "testnet"

# Staging deployments (all branches)
[context.branch-deploy]
  [context.branch-deploy.environment]
    REACT_APP_MODE = "mainnet"

# Testnet deployment
[context.dev]
  [context.dev.environment]
    REACT_APP_MODE = "testnet"
