export enum Asset {
  ETH = 'eth',
  ETHs = 'eths',
  BNB = 'bnb',
  BNBs = 'bnbs',
  SOV = 'sov',
  eSOV = 'esov',
  bSOV = 'bsov',
  WBTC = 'wbtc',
  DAI = 'dai',
  USDC = 'usdc',
  USDT = 'usdt',
  BUSD = 'busd',
  XUSD = 'xusd',
}
