name: Test if builds successfully
on:
  pull_request:
    branches: [development]
  push:
    branches: [development]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          yarn --frozen-lockfile
          yarn build
